# Generated by Django 4.2.4 on 2025-05-10 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_used', models.IntegerField(default=0)),
                ('annual_leave_used', models.IntegerField(default=0)),
                ('sick_leave_used', models.IntegerField(default=0)),
                ('exam_leave_used', models.IntegerField(default=0)),
                ('maternity_leave_used', models.IntegerField(default=0)),
                ('compassionate_leave_used', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('AL', 'Annual Leave'), ('SL', 'Sick Leave'), ('EL', 'Exam/Study Leave'), ('ML', 'Maternity Leave'), ('CPL', 'Compassionate Leave')], max_length=3)),
                ('year', models.IntegerField()),
                ('purpose', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('hod_or_line_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_or_line_manager', to=settings.AUTH_USER_MODEL)),
                ('relief_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_officer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
