# Generated by Django 4.2.4 on 2025-03-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HELPForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('HQ_Lekki', 'HQ Lekki'), ('CGS_Ikorodu', 'CGS Ikorodu'), ('LNG_PH', 'LNG PH'), ('LFZ_Ibeju', 'LFZ Ibeju')], max_length=255, null=True)),
                ('issue', models.CharField(blank=True, choices=[('IT', 'IT Support')], max_length=255, null=True)),
                ('priority', models.CharField(blank=True, choices=[('High', 'HIGH'), ('Low', 'LOW'), ('Medium', 'MEDIUM'), ('Normal', 'NORMAL')], max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('complaint', models.TextField(null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('Closed', 'Closed')], default='pending', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
