# Generated by Django 4.2.4 on 2025-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_helpform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpform',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpform',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='helpform',
            name='response_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
