# Generated by Django 4.2.4 on 2025-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_helpform_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpform',
            name='location',
            field=models.CharField(blank=True, choices=[('HQ_Lekki', 'HQ Lekki'), ('CGS_Ikorodu', 'CGS Ikorodu'), ('LPG_PH', 'LPG PH'), ('LFZ_Ibeju', 'LFZ Ibeju')], max_length=255, null=True),
        ),
    ]
