# Generated by Django 4.2.4 on 2025-02-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_ptwform_manager_date_ptwform_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhisform',
            name='dept',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('BDS', 'BDS'), ('DC', 'DC'), ('ER', 'ER'), ('FVC', 'FVC'), ('HR', 'HR'), ('HSE', 'HSE'), ('IAC', 'IAC'), ('IT', 'IT'), ('LRC', 'LRC'), ('TS', 'TS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nhisform',
            name='location',
            field=models.CharField(blank=True, choices=[('HQ_Lekki', 'HQ_Lekki'), ('CGS_Ikorodu', 'CGS_Ikorodu'), ('LNG_PH', 'LNG_PH'), ('LFZ_Ibeju', 'LFZ_Ibeju')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nhisform',
            name='responsible_party',
            field=models.CharField(choices=[('HSEQ', 'HSEQ')], default='HSEQ', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='nhisform',
            name='risk_type',
            field=models.CharField(blank=True, choices=[('UA', 'UA (Unsafe Act)'), ('UC', 'UC (Unsafe Condition)'), ('NM', 'NM (Near Miss)'), ('ACD', 'ACD (Accident)'), ('NC', 'NC (Non-Conformity)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ptwform',
            name='certificates_required',
            field=models.CharField(blank=True, choices=[('CERTIFICATE_FOR_EXCAVATION_WORK', 'CERTIFICATE_FOR_EXCAVATION_WORK'), ('CERTIFICATE_FOR_HOT_WORK', 'CERTIFICATE_FOR_HOT_WORK'), ('CERTIFICATE_FOR_ELECTRICAL_WORK', 'CERTIFICATE_FOR_ELECTRICAL_WORK'), ('GAS_TEST_FORM', 'GAS_TEST_FORM'), ('CERTIFICATE_FOR_CONFINED_SPACES', 'CERTIFICATE_FOR_CONFINED_SPACES'), ('NOT_APPLICABLE', 'NOT_APPLICABLE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ptwform',
            name='location',
            field=models.CharField(blank=True, choices=[('HQ_Lekki', 'HQ_Lekki'), ('CGS_Ikorodu', 'CGS_Ikorodu'), ('LNG_PH', 'LNG_PH'), ('LFZ_Ibeju', 'LFZ_Ibeju')], max_length=255, null=True),
        ),
    ]
