# Generated by Django 4.2.4 on 2025-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_nhisform_dept_alter_nhisform_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptwform',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='project_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
