# Generated by Django 4.2.4 on 2025-04-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
