# Generated by Django 4.2.4 on 2025-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhisform',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='nhisform',
            name='observed_date',
        ),
        migrations.RemoveField(
            model_name='nhisform',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nhisform',
            name='ram_rating',
        ),
        migrations.RemoveField(
            model_name='nhisform',
            name='responsible_party',
        ),
        migrations.RemoveField(
            model_name='nhisform',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='nhisform',
            name='target_date',
        ),
        migrations.AddField(
            model_name='nhisform',
            name='activity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='other_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
